/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JConnConfig.java
 *
 * Created on 04/04/2009, 16:12:27
 */
package com.edusasse.visualsql.gui;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListDataListener;

import com.edusasse.visualsql.db.jdbc.ConnController;
import com.edusasse.visualsql.db.jdbc.ConnectionHandler;
import com.edusasse.visualsql.db.jdbc.MyDriver;
import com.edusasse.visualsql.gui.conntree.MyTreeListener;

@SuppressWarnings("serial")
public class ConnConfig extends javax.swing.JPanel {

    MyTreeListener tree;
    private boolean editing = false;

    /** Creates new form JConnConfig */
    public ConnConfig(MyTreeListener tree) {
        this.tree = tree;
        initComponents();
        this.txtConnName.requestFocus();
        jcmLibaries.addItemListener(new ItemListener() {

            @SuppressWarnings("static-access")
			@Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == e.SELECTED) {
                    txtUrl.setText(((MyDriver) e.getItemSelectable().getSelectedObjects()[0]).getExample());
                }
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {

        txtConnName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jcmLibaries = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        ckAutoConn = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        ckAutoSaveOnExit = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        ckSavePass = new javax.swing.JCheckBox();
        ckLoadMetaDataOnConnect = new javax.swing.JCheckBox();

        txtConnName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConnNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("Driver JDBC:");

        jcmLibaries.setModel(new MyComboModel());

        jLabel3.setText("URL:");

        ckAutoConn.setText("Auto Conectar ao Abrir?");
        ckAutoConn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckAutoConnActionPerformed(evt);
            }
        });

        jButton1.setForeground(new java.awt.Color(0, 102, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accept.png"))); // NOI18N
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cross.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ckAutoSaveOnExit.setSelected(true);
        ckAutoSaveOnExit.setText("Salvar Conexao ao Sair?");
        ckAutoSaveOnExit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accept.png"))); // NOI18N
        ckAutoSaveOnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckAutoSaveOnExitActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setText("Criando uma Conexao JDBC");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fdf.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(308, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Seguranca:"));

        jLabel6.setText("Usuario:");

        jLabel7.setText("Senha:");

        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        ckSavePass.setText("Salvar Senha?");
        ckSavePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckSavePassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckSavePass)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ckSavePass))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap())))
        );

        ckLoadMetaDataOnConnect.setSelected(true);
        ckLoadMetaDataOnConnect.setText("Carregar Meta Dados ao Conectar?");
        ckLoadMetaDataOnConnect.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accept.png"))); // NOI18N
        ckLoadMetaDataOnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckLoadMetaDataOnConnectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtConnName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcmLibaries, 0, 342, Short.MAX_VALUE)
                    .addComponent(txtUrl, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
                .addGap(167, 167, 167))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(ckAutoConn)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckLoadMetaDataOnConnect)
                    .addComponent(ckAutoSaveOnExit))
                .addGap(314, 314, 314))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(317, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(344, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtConnName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcmLibaries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckAutoConn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckAutoSaveOnExit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckLoadMetaDataOnConnect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void txtConnNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConnNameActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtConnNameActionPerformed

    private void ckAutoConnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckAutoConnActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_ckAutoConnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.verfCampos() == true) {
            Hashtable<String, Object> par = new Hashtable<String, Object>();
            par.put("AUTO_SAVE_ON_EXIT", new Boolean(this.ckAutoSaveOnExit.isSelected()));
            par.put("SAVE_PASSWORD", new Boolean(this.ckSavePass.isSelected()));
            par.put("AUTO_CONNECT_ON_OPEN", new Boolean(this.ckAutoConn.isSelected()));
            par.put("LOAD_META_DATA", new Boolean(this.ckLoadMetaDataOnConnect.isSelected()));
            try {
                if (isEditing()) {
                    ConnController.removeHandler(this.txtConnName.getText().trim());
                }
                ConnController.open(this.jcmLibaries.getSelectedItem().toString(), this.txtConnName.getText().trim(), this.txtUrl.getText(), this.txtUser.getText().trim(), String.valueOf(this.txtPass.getPassword()), par);
                GUIController.getInstance().getMain().removeConn(this);
                tree.newConnAdd();

            } catch (Exception ex) {
                Logger.getLogger(ConnConfig.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        GUIController.getInstance().saveProfileConn();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ckAutoSaveOnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckAutoSaveOnExitActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_ckAutoSaveOnExitActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtUserActionPerformed

    private void ckSavePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckSavePassActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_ckSavePassActionPerformed

    private void ckLoadMetaDataOnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckLoadMetaDataOnConnectActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_ckLoadMetaDataOnConnectActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        GUIController.getInstance().getMain().removeConn(this);
    }//GEN-LAST:event_jButton2ActionPerformed
    private boolean verfCampos() {
        if (this.txtConnName.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Faltou preencher o nome da conexao!");
            return false;
        } else if (this.txtUrl.getText().trim().equals("") || this.jcmLibaries.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Faltou preencher a URL de conexao!");
            return false;
        }
        return true;
    }

    class MyComboModel implements ComboBoxModel {

        Object s = null;

        @Override
        public void setSelectedItem(Object anItem) {
            s = anItem;
        }

        @Override
        public Object getSelectedItem() {
            return s;
        }

        @Override
        public int getSize() {
            return ConnController.getDeclaredDriversKeys().length;
        }

        @Override
        public Object getElementAt(int index) {
            return ConnController.getDrivers(ConnController.getDeclaredDriversKeys()[index].toString());
        }

        @Override
        public void addListDataListener(ListDataListener l) {
            // throw new UnsupportedOperationException("Not supported yet.");
        }

        @Override
        public void removeListDataListener(ListDataListener l) {
            // throw new UnsupportedOperationException("Not supported yet.");
        }
    }

    private void setEditing() {
        this.editing = true;
    }

    private boolean isEditing() {
        return editing;
    }

    public void setEdit(ConnectionHandler ch) {
        this.setEditing();
        this.txtConnName.setText(ch.getKey());
        this.txtConnName.setEditable(false);

        for (int i = 0; i < this.jcmLibaries.getItemCount(); i++) {
            if (this.jcmLibaries.getItemAt(i).toString().equals(ch.getDriverClass().toString())) {
                this.jcmLibaries.setSelectedIndex(i);
            }
        }

        this.txtUrl.setText(ch.getUrl());
        this.ckSavePass.setSelected(ch.isSavePassword());
        this.ckAutoConn.setSelected(ch.isAutoConnectOnOpen());
        this.ckAutoSaveOnExit.setSelected(ch.isAutoSaveOnExit());
        this.ckLoadMetaDataOnConnect.setSelected(ch.isLoadMetaDataOnConnect());
        this.txtUser.setText(ch.getInfo().getProperty("user"));
        this.txtPass.setText(ch.getInfo().getProperty("password"));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ckAutoConn;
    private javax.swing.JCheckBox ckAutoSaveOnExit;
    private javax.swing.JCheckBox ckLoadMetaDataOnConnect;
    private javax.swing.JCheckBox ckSavePass;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox jcmLibaries;
    private javax.swing.JTextField txtConnName;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUrl;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
